---
- name:             "Build hosts file"
  lineinfile:       dest=/etc/hosts
                    regexp='.*{{ item.hostname }}$'
                    line="{{ item.ipadres }} {{ item.hostname }}"
                    state=present
  with_items:       "{{ etc_hostnames }}"
